update the templates and tasks for role of zookeeper.

diff --git a/roles/zookeeper/templates/init_zookeeper.sh.j2 b/roles/zookeeper/templates/init_zookeeper.sh.j2
--- a/roles/zookeeper/templates/init_zookeeper.sh.j2
+++ b/roles/zookeeper/templates/init_zookeeper.sh.j2
@@ -4,14 +4,14 @@
 export PS4='+ [`basename ${BASH_SOURCE[0]}`:$LINENO ${FUNCNAME[0]} \D{%F %T} $$ ] '
 
 prefixdir=/opt/zookeeper
-zoocfg=/etc/zookeeper/conf/zoo.cfg
+#zoocfg=/etc/zookeeper/conf/zoo.cfg
 
 ######## install zookeeper
-yum install -y zookeeper.x86_64 zookeeper-server.x86_64 --nogpgcheck
-if [ $? -ne 0 ]; then
-    echo "Install zookeeper failed."
-    exit 1
-fi
+#yum install -y zookeeper.x86_64 zookeeper-server.x86_64 --nogpgcheck
+#if [ $? -ne 0 ]; then
+#    echo "Install zookeeper failed."
+#    exit 1
+#fi
 
 ######## change zookeeper data dir.
 mkdir -p ${prefixdir}/{data,log}
@@ -29,7 +29,8 @@ sed -i "s#export ZOO_LOG_DIR=.*#export ZOO_LOG_DIR=\${ZOO_LOG_DIR:-${prefixdir}/
 #EOF
 
 ######## initialize zookeeper myid
-myid=`ifconfig | grep "inet addr:10\." | grep -oP "((\d+\.)){3}(\d+)" | head -n 1 | awk -F\. '{print $NF}'`
+#myid=`ifconfig | grep "inet addr:10\." | grep -oP "((\d+\.)){3}(\d+)" | head -n 1 | awk -F\. '{print $NF}'`
+myid=$(cat /etc/zookeeper/conf.dist/myid)
 zookeeper-server-initialize --myid=${myid}
 if [ $? -ne 0 ]; then
     echo "Initialize zookeeper myid failed."
